### ISSUE TITLE
pretrained darknet-light model

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/yolov2-yolov3_PyTorch#36]
Hi!

Could you upload the pretrained darknet-light model?

**Comment by yjh0410** [comment]
OK!
I upload darknet-light and darknet-light-448 just now. You can download it~

**Comment by developer0hye** [comment]
Ok! After downlaod it, I will upload it on google drive, too.

**Comment by yjh0410** [comment]
Thanks a lot！



---Original---
