### ISSUE TITLE
mAP of yolov3-tiny on VOC

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/yolov2-yolov3_PyTorch#38]
Hi, yjh!
It's been a while.

Have you ever measured the mAP of yolov3-tiny on VOC?

**Comment by yjh0410** [comment]
Hi! Long time no see!
The mAP on VOC,, emmm..... I remember that it's about 60+ mAP. 
I'm not sure......Sorry~

**Comment by developer0hye** [comment]
@yjh0410 
Thanks~! 
I finished my M.S course.
Your code helped me to graduate graduate school.

**Comment by yjh0410** [comment]
Congratulations!
I sincerely wish you more and more success in the future！
어서!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yjh0410/yolov2-yolov3_PyTorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月13日(星期天) 晚上9:57
收件人:&nbsp;"yjh0410/yolov2-yolov3_PyTorch"<yolov2-yolov3_PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/yolov2-yolov3_PyTorch] mAP of yolov3-tiny on VOC (#38)





 
@yjh0410
 Thanks~!
 I finished my M.S course.
 Your code helped me to graduate school.

**Comment by developer0hye** [comment]
@yjh0410 
Thanks!! Haha.

[My yolov3 tiny model](https://github.com/developer0hye/YOLOv3Tiny) reached mAP 53.7.



```
67.65% = aeroplane AP
70.54% = bicycle AP
47.78% = bird AP
37.30% = boat AP
24.25% = bottle AP
58.53% = bus AP
70.95% = car AP
61.54% = cat AP
29.46% = chair AP
55.86% = cow AP
43.19% = diningtable AP
57.06% = dog AP
66.56% = horse AP
68.29% = motorbike AP
63.59% = person AP
22.71% = pottedplant AP
55.82% = sheep AP
47.61% = sofa AP
65.59% = train AP
55.84% = tvmonitor AP
mAP = 53.51%
```

My model cannot detect pottedplant, chair, bottle, and boat well.
Have you ever had this problem?

**Comment by yjh0410** [comment]
Thanks a lot ！！
I tried again on my devices, and got almost same result without multi-scale trick.

Maybe my tiny yolov3 is really too tiny to perform well.

The official tiny yolov3 doesn't provide its mAP on VOC, only the AP50 on COCO, so I don't have a reference to judge the quality of my model.

**Comment by developer0hye** [comment]
@yjh0410 
Thanks a lot~!!
Okay, it seems that the representation power of yolov3 tiny is too weak, so that model failed to detect some objects.
When I found official yolov3 tiny's the mAP on VOC, I couldn't find this. So, I asked you this. You are the one of the experts about detection algorithms that I know!

**Comment by yjh0410** [comment]
As far as I know，there‘s no information about tiny v3 on VOC.

It’s so weak that it isn't good at detecting many kinds of objects. Unless there is just one class like person or cat，tiny v3 can work well.

**Comment by developer0hye** [comment]
@yjh0410 
Thanks!
