### ISSUE TITLE
Normalization 

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/yolov2-yolov3_PyTorch#41]
https://github.com/yjh0410/yolov2-yolov3_PyTorch/blob/63db94a19027eac3ee3922e3172e1c7680af33f9/utils/augmentations.py#L419

Hi! It's been a long time.

Did you compare the performance with or without normalization?

**Comment by yjh0410** [comment]
Hello！ Long time no see.

Yeah, I tried this, and I found that the detector with normalization worked better.

**Comment by developer0hye** [comment]
@yjh0410 
Do you remember the detailed improvement like +1.3 mAP??

**Comment by yjh0410** [comment]
So sorry~I forget it~

**Comment by developer0hye** [comment]
@yjh0410 
Thanks :+1:
