### ISSUE TITLE
Why using sigmoid when decode_xy?

### ISSUE THREAD

**Issue by chenslcool** [yjh0410/yolov2-yolov3_PyTorch#49]
https://github.com/yjh0410/yolov2-yolov3_PyTorch/blob/7fab455b29dcc70b1615461472f35f2c7772020f/models/yolov2_r50.py#L75

According to generate_txtytwth(), there's no corresponding operation of sigmoid.

**Comment by yjh0410** [comment]
The label of txty ranges from 0 to 1 which you can see from the `generate_txtytwth()` function, so I use the sigmoid to ensure the predicted txty also ranges from 0 to 1.

**Comment by chenslcool** [comment]
thanks
